version: "3.6"
services:
  redis_7001:
    image: redis:5.0
    container_name: redis_7001
    command: ["redis-server", "/home/redis/cluster/7001/redis.conf"]
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - /data/redis-cluster/config/7001/redis.conf:/home/redis/cluster/7001/redis.conf
      - /data/redis-cluster/data/7001:/data
    networks:
      - redis_cluster

  redis_7002:
    image: redis:5.0
    container_name: redis_7002
    command: ["redis-server", "/home/redis/cluster/7002/redis.conf"]
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - /data/redis-cluster/config/7002/redis.conf:/home/redis/cluster/7002/redis.conf
      - /data/redis-cluster/data/7002:/data
    networks:
      - redis_cluster

  redis_7003:
    image: redis:5.0
    container_name: redis_7003
    command: ["redis-server", "/home/redis/cluster/7003/redis.conf"]
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - /data/redis-cluster/config/7003/redis.conf:/home/redis/cluster/7003/redis.conf
      - /data/redis-cluster/data/7003:/data
    networks:
      - redis_cluster

  redis_7004:
    image: redis:5.0
    container_name: redis_7004
    command: ["redis-server", "/home/redis/cluster/7004/redis.conf"]
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - /data/redis-cluster/config/7004/redis.conf:/home/redis/cluster/7004/redis.conf
      - /data/redis-cluster/data/7004:/data
    networks:
      - redis_cluster

  redis_7005:
    image: redis:5.0
    container_name: redis_7005
    command: ["redis-server", "/home/redis/cluster/7005/redis.conf"]
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - /data/redis-cluster/config/7005/redis.conf:/home/redis/cluster/7005/redis.conf
      - /data/redis-cluster/data/7005:/data
    networks:
      - redis_cluster

  redis_7006:
    image: redis:5.0
    container_name: redis_7006
    command: ["redis-server", "/home/redis/cluster/7006/redis.conf"]
    ports:
      - 7006:7006
      - 17006:17006
    volumes:
      - /data/redis-cluster/config/7006/redis.conf:/home/redis/cluster/7006/redis.conf
      - /data/redis-cluster/data/7006:/data
    networks:
      - redis_cluster

networks:
  redis_cluster:
    driver: bridge
